### ISSUE TITLE
Java 15+ compatibility

### ISSUE THREAD

**Issue by ztNFny** [littleyoda/hibiscus.depotviewer#131]
Java 15+ doesn't package nashorn anymore, thus with java 17 (LTS) or 21 (current) you get:

[ERROR][main][de.open4me.depot.DepotViewerPlugin.checkJavaStockQuotesDirectory] Fehler beim Laden von ariva.js
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "engine" is null
        at jsq.fetcher.history.GenericJSFetcher.<init>(GenericJSFetcher.java:40)
        at jsq.fetch.factory.Factory.addJSFetcher(Factory.java:41)
        at de.open4me.depot.DepotViewerPlugin.checkJavaStockQuotesDirectory(DepotViewerPlugin.java:55)
        at de.open4me.depot.DepotViewerPlugin.init(DepotViewerPlugin.java:39)
        at de.willuhn.jameica.plugin.PluginLoader.initPlugin(PluginLoader.java:394)
        at de.willuhn.jameica.plugin.PluginLoader.init(PluginLoader.java:239)
        at de.willuhn.jameica.services.PluginService.init(PluginService.java:39)
        at de.willuhn.boot.BootLoader.resolve(BootLoader.java:139)
        at de.willuhn.boot.BootLoader.resolve(BootLoader.java:119)
        at de.willuhn.boot.BootLoader.getBootable(BootLoader.java:70)
        at de.willuhn.jameica.system.Application.init(Application.java:103)
        at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
        at de.willuhn.jameica.Main.main(Main.java:78)

Solution: In your dependencies (usually e.g. a maven pom.xml, but I don't see any build system file in this repo??) add:
```
<dependency>
    <groupId>org.openjdk.nashorn</groupId>
    <artifactId>nashorn-core</artifactId>
</dependency>
```

**Comment by faiteanu** [comment]
@littleyoda There is a new version of JavaStockQuotes which does not rely on Nashorn anymore.
Please replace v0.1.2 with java-stock-quotes-0.1.4.jar from https://github.com/faiteanu/JavaStockQuotes/releases/tag/v0.1.4
