### ISSUE TITLE
Fehlermeldung bei der G+V im Depotviewer

### ISSUE THREAD

**Issue by github-ps1304** [littleyoda/hibiscus.depotviewer#137]
Beim Aufruf der G-V Rechnung (Inkonsistenz anzeigen) bekomme ich eine Fehlermeldung:

`ava.lang.IllegalArgumentException: Argument not valid Referenz zu Entity "P" muss mit dem Begrenzungszeichen ";" enden.
	at org.eclipse.swt.SWT.error(SWT.java:4899)
	at org.eclipse.ui.internal.forms.widgets.FormTextModel.parseInputStream(FormTextModel.java:133)
	at org.eclipse.ui.internal.forms.widgets.FormTextModel.parseTaggedText(FormTextModel.java:111)
	at org.eclipse.ui.forms.widgets.FormText.setText(FormText.java:673)
	at de.willuhn.jameica.gui.parts.FormTextPart.refresh(FormTextPart.java:135)
	at de.willuhn.jameica.gui.parts.FormTextPart.paint(FormTextPart.java:235)
	at de.open4me.depot.gui.view.BestandsAbgleichView.bind(BestandsAbgleichView.java:25)
	at de.willuhn.jameica.gui.GUI$5.run(GUI.java:724)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:921)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5960)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:917)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:601)
	at de.willuhn.jameica.gui.GUI.startView(GUI.java:536)
	at de.open4me.depot.gui.view.BewertungsView$1.handleAction(BewertungsView.java:38)
	at de.willuhn.jameica.gui.parts.Button$1$1.run(Button.java:174)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:921)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5960)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:917)
	at de.willuhn.jameica.gui.parts.Button$1.widgetSelected(Button.java:168)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:938)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:335)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:78)`

**Comment by github-ps1304** [comment]
tritt bei mir immer noch auf der Fehler

**Comment by littleyoda** [comment]
Kannst du mir bitte nochmal die Fehlermeldung schicken?

**Comment by github-ps1304** [comment]
gerne doch:

<img width="736" height="621" alt="Image" src="https://github.com/user-attachments/assets/9b601763-e56a-49e4-97e1-121f2f9bbddd" />

**Comment by github-ps1304** [comment]
gerne doch:

<img width="601" height="271" alt="Image" src="https://github.com/user-attachments/assets/cbea6f92-ca6d-4fc8-9418-9ba5d0c80599" />
