### ISSUE TITLE
Consors JSON error

### ISSUE THREAD

**Issue by Massimo-B** [littleyoda/hibiscus.depotviewer#51]
I finally managed to get the Consors fetch working. I have 2 different depots, one is working, the other fails with this error log:

```
[Mon Jul 18 11:48:14 CEST 2016][INFO][de.open4me.depot.abruf.impl.CortalConsorsMitHBCI.run] Starte Screen Scraping für Cortal Consors
[Mon Jul 18 11:48:16 CEST 2016][INFO][de.open4me.depot.abruf.utils.HtmlUtils.setProxyCfg] Using system proxy settings: [HTTP @ gate01:8080]
[Mon Jul 18 11:48:16 CEST 2016][INFO][de.open4me.depot.abruf.utils.HtmlUtils.setProxyCfg] Setting Proxy to com.gargoylesoftware.htmlunit.ProxyConfig@6e7a9c72
[Mon Jul 18 11:48:17 CEST 2016][INFO][de.open4me.depot.abruf.impl.CortalConsorsMitHBCI.runUmsaetze] JSON für Order: ...
[Mon Jul 18 11:48:18 CEST 2016][ERROR][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.markExecutedInternal] unable to mark job as executed
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at de.open4me.depot.abruf.impl.CortalConsorsMitHBCIJSONWrapper.getWkn(CortalConsorsMitHBCIJSONWrapper.java:116)
	at de.open4me.depot.abruf.impl.CortalConsorsMitHBCIJSONWrapper.addUmsatz(CortalConsorsMitHBCIJSONWrapper.java:49)
	at de.open4me.depot.abruf.impl.CortalConsorsMitHBCI.runUmsaetze(CortalConsorsMitHBCI.java:136)
	at de.open4me.depot.abruf.impl.CortalConsorsMitHBCI.run(CortalConsorsMitHBCI.java:54)
	at de.open4me.depot.hbcijobs.HBCIDepotBestandJob.markExecuted(HBCIDepotBestandJob.java:136)
	at de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.markExecutedInternal(AbstractHBCIJob.java:326)
	at de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.handleResult(AbstractHBCIJob.java:267)
	at de.willuhn.jameica.hbci.synchronize.hbci.HBCISynchronizeBackend$HBCIJobGroup.sync(HBCISynchronizeBackend.java:338)
	at de.willuhn.jameica.hbci.synchronize.AbstractSynchronizeBackend$Worker.run(AbstractSynchronizeBackend.java:388)
	at de.willuhn.jameica.gui.GUI$7.run(GUI.java:1057)

[Mon Jul 18 11:48:18 CEST 2016][WARN][de.willuhn.jameica.hbci.synchronize.hbci.HBCISynchronizeBackend$HBCIJobGroup.sync] found errors or synchronization cancelled, clear PIN cache
```
I removed the JSON string with private data in the log, if you need more information, please contact me.

**Comment by littleyoda** [comment]
korrigiert mit der 0.3.39

**Comment by Massimo-B** [comment]
Saldo Abruf funktioniert nun. Umsätze werden aber keine abgerufen, obwohl beides in den Optionen angehakt ist. Web-Zugang ist in den Einstellungen des Depot-Viewer auch hinterlegt.

**Comment by littleyoda** [comment]
Für eine weitere Diagnose, benötige ich ein aktuelles Logfile

**Comment by littleyoda** [comment]
Laut Rückmeldung tauchen die Order im Orderbuch auf. So wie es sein sollte.

Order tauchen nicht unter Umsätzen auf.
