### ISSUE TITLE
Integration mit https://github.com/bmhm/hibiscus.ffb.depot

### ISSUE THREAD

**Issue by bmarwell** [littleyoda/hibiscus.depotviewer#53]
Hi,

bei meinem Plugin (https://github.com/bmhm/hibiscus.ffb.depot) Stellt man auch auf Typ (egal, Wertpapierdepot oder Fonds-Depot). Wichtig ist bei meinem Plugin die BIC/BLZ.

Zugang ist "PIN/TAN (non-HBCI)".

Leider taucht es nicht von alleine auf. Was können wir gemeinsam tun, damit das Depot auftaucht, wenn das ffb.depot-Plugin installiert ist?

Gruß

**Comment by littleyoda** [comment]
Mein Depotviewer unterstützt (noch?) keine weiteren Plugins, da es für Depots keine echte Unterstützung in Hibiscus gibt.

Ich schaue aber mal, ob ich deine Libary in den Depotviewer integrieren kann.

**Comment by littleyoda** [comment]
Noch als Hinweis: Wenn du "PIN/TAN (non-HBCI)" nutzt, setzt es die Plugins von Sebastian voraus.
In Hibiscus gibt es keine einfache und gute Möglichkeit, die Passwörter für Plugins zu verwalten.

**Comment by bmhm** [comment]
Welchen Weg da gegangen wird ist dem Client sowieso egal. Das hibiscus-Plugin ist aber auch nicht daran gebunden. Statt meine Library direkt zu integrieren wäre vielleicht eine Pluginarchitektur sinnvoll. Zumindest gibt es die erste Version schon in Maven Central. Ich hoffe, du benutzt ivy, Maven oder Gradle? 

Wenn du im client etwas vermisst (Doku oder Funktionen), stell mir gerne einen Issue ein. :+1:

**Comment by bmhm** [comment]
Hallo,

hast Du evtl. Zeit, die Library bei Zeiten zu integrieren? Ich habe nun folgenden Zeitplan:

- Pflege einer Release 1.0.0-Version, wenn ich [alle Issues zu 1.0.0](https://github.com/bmhm/ffb.depot.client/milestone/1) gelöst habe.
- Ab Version 2.0.0 werde ich einen Branch mit Java 8 anbieten, der [CompletableFuture<>](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) zurückgibt. Den 1.x-er Branch werde ich aber weiterpflegen.
- Ab Version 2.0.0 werde ich Jax-RS als Backend nutzen.

Freue mich auf die Integration. Historische Umsätze sind gerade unterwegs.

**Comment by littleyoda** [comment]
Ich habe mich gerade mal an einer Integration versucht.

Leider erhalte ich den folgenden Fehler. Hast du deine Implementierung in den letzten Tagen mal getestet?


`javax.ws.rs.ProcessingException: Error reading entity from input stream.
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:889)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:321)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:389)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:264)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
	at de.bmarwell.ffb.depot.client.FfbMobileClient.getPerformance(FfbMobileClient.java:144)
	at de.open4me.depot.abruf.impl.FfbDepot.run(FfbDepot.java:62)
	at de.open4me.depot.abruf.www.DVSynchronizeJobKontoauszug.execute(DVSynchronizeJobKontoauszug.java:37)
	at de.open4me.depot.abruf.www.DVSynchronizeBackend$MMTgJobGroup.sync(DVSynchronizeBackend.java:160)
	at de.willuhn.jameica.hbci.synchronize.AbstractSynchronizeBackend$Worker.run(AbstractSynchronizeBackend.java:396)
	at de.willuhn.jameica.gui.GUI$7.run(GUI.java:1057)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Format of GermanDate != dd.mm.yyyy (through reference chain: de.bmarwell.ffb.depot.client.json.ImmutableFfbPerformanceResponse$Json["ersterZufluss"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1704)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058)
	at de.bmarwell.ffb.depot.client.util.JacksonMessageBodyReader.readFrom(JacksonMessageBodyReader.java:41)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:257)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	... 15 more
Caused by: java.lang.IllegalArgumentException: Format of GermanDate != dd.mm.yyyy
	at de.bmarwell.ffb.depot.client.util.GermanDateToLocalDateDeserializer.deserialize(GermanDateToLocalDateDeserializer.java:61)
	at de.bmarwell.ffb.depot.client.util.GermanDateToLocalDateDeserializer.deserialize(GermanDateToLocalDateDeserializer.java:30)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	... 28 more
`

**Comment by bmhm** [comment]
Kannst du den Stacktrace bitte nochmal formatiert posten?

Dazu nutzt du 3x ` 

Danke.

PS: Hast du die aktuelle Version? Von maven central?

**Comment by littleyoda** [comment]
Habs geändert.

Habe die Github-Version selber kompiliert.

**Comment by littleyoda** [comment]
FFB Unterstützung entfernt

**Comment by bmarwell** [comment]
Die API gibts ja schon lange nicht mehr…
