### ISSUE TITLE
ING-DIBA-Depot-Abfrage Wertpapiere fehlen, Records gelöscht

### ISSUE THREAD

**Issue by WS42Hi** [littleyoda/hibiscus.depotviewer#80]
ING-DIBA-Depot-Abfrage Records aus Tabelle DEPOTVEWER_BESTAND gelöscht

1. synchronisiere ING-DIBA-Depot
2. erhalte Fehlermeldung
     [26.11.2019 14:25:06] Aufträge ausgeführt
     [26.11.2019 14:25:06] Fehlermeldung der Bank: 
     0020 - Der Auftrag wurde ausgeführt.
     [26.11.2019 14:25:06] Es sind Fehler aufgetreten
3. Depotviewer->Bestand meldet: Inkonsistenzen zwischen Umsätzen und Beständen
4. zwei Wertpapier fehlen in der Bestandsliste
5. Per SQL die Tabelle DEPOTVEWER_BESTAND geprüft:
    Es fehlen die 2 Records für die fehlenden Wertpapiere. In Tabelle DEPOTVIEWER_WERTPAPIER sind 
    sie vorhanden.
6. Aus Backup per SQL die Records wieder eingefügt
7. Depotviewer->Bestand  ohne Fehlermeldung
8. synchronisiere ING-DIBA-Depot
9. Fehlerbild ( 2. - 5. )  wiederholt sich mit den selben Wertpapieren
10. schaue mir hbcitrace.log an: Finde nichts auffälliges

Der Fehler ist reproduzierbar.
Nutze DEPOTVIEWER seit 2 Jahren, alles war gut! 
?????

hibiscus 2.8.21
depotviewer 0.5.7
WIN 10

**Comment by WS42Hi** [comment]
Ergänzung:
Habe in jameica.log fast die gleiche ERROR-Meldung gefunden, wie im Beitrag 
[https://forum.open4me.de/viewtopic.php?t=106](url)
[Wed Nov 27 13:51:41 CET 2019][ERROR][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.markExecutedInternal] unable to mark job as executed
java.lang.NullPointerException at de.open4me.depot.hbcijobs.HBCIDepotBestandJob.markExecuted(HBCIDepotBestandJob.java:122)
	at de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.markExecutedInternal(AbstractHBCIJob.java:409)

**Comment by WS42Hi** [comment]
Funktioniert wieder :-)
ING-DiBA hat wohl etwas geändert?
